<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/1280px-NumPy_logo_2020.svg.png" alt="numpy" width="400">

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

# Introduction to Numpy

The Numpy lib is the numeric library of Python, and is the basis of all the large libraries of the Python ecosystem of Computational Science and Data Analysis, such as Scipy, Matplotlib and Pandas. The library creates a new data structure, called "ndarray", that has some similarities with lists, but a few more powers, with emphasis on the ability to vectorize, that allows the computational operation more efficient.

### Import libraries

In [1]:
import numpy as np

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Numpy Array

In [2]:
np.array([-2, 4.3, 7, 9])

array([-2. ,  4.3,  7. ,  9. ])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Methods to create a numpy array:

**1. Using the list object:**

In [3]:
arr = np.array([-2, 3, 4.5, 9])
arr

array([-2. ,  3. ,  4.5,  9. ])

PS: Note that Numpy transforms all numbers to float through the "upcasting" system, in other words, the Numpy array is a homogeneous array.

The upcasting operation takes place with the following priority: string > complex > float > int

**2. Using the arange method:**

In [4]:
arr = np.arange(1, 32, 2)
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31])

*Parameters of the arange method:*
<br>
`np.arange(begin, end, step)`
<br>
PS: Like the Python range, the end does not include it.

**3. Using the linspace:**

In [5]:
arr = np.linspace(1, 100, 10)
arr

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

PS: Note that was created an array of 10 equally spaced values, where the first value is 1, and the last is 100.
<br>
`np.linspace(begin, end, quantity)`


**4. Other methods:**

- The empty() function is used to create a new array of given shape and type, without initializing entries.

In [6]:
arr1 = np.empty(10)
print(arr1)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


- The eye() function is used to create a 2-D array with ones on the diagonal and zeros elsewhere.

In [7]:
arr2 = np.eye(4)
print(arr2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


- The zeros() function is used to get a new array of given shape and type, filled with zeros.

In [8]:
arr3 = np.zeros(8, int)
print(arr3)

[0 0 0 0 0 0 0 0]


- The ones() function is used to get a new array of given shape and type, filled with ones

In [9]:
arr4 = np.ones((4, 3))
print(arr4)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Numpy Array Operations

In [10]:
A = np.arange(10)
B = np.arange(2, 12)
C = np.array([2,3,4,5,6,7,8,9,np.nan, np.nan])

print("A: ",A)
print("B: ",B)
print("C: ",C)

A:  [0 1 2 3 4 5 6 7 8 9]
B:  [ 2  3  4  5  6  7  8  9 10 11]
C:  [ 2.  3.  4.  5.  6.  7.  8.  9. nan nan]


In [11]:
D = A+C
print("D: ",D)

D:  [ 2.  4.  6.  8. 10. 12. 14. 16. nan nan]


In [12]:
addition = A + B
addition

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [13]:
subtraction = A - B
subtraction

array([-2, -2, -2, -2, -2, -2, -2, -2, -2, -2])

In [14]:
division = A / B
division

array([0.        , 0.33333333, 0.5       , 0.6       , 0.66666667,
       0.71428571, 0.75      , 0.77777778, 0.8       , 0.81818182])

In [15]:
multiplication = A * B
multiplication

array([ 0,  3,  8, 15, 24, 35, 48, 63, 80, 99])

In [16]:
new_A = A * 10
new_A

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [17]:
new_A > 40

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Numpy Indexing

![Image of Yaktocat](http://www.scipy-lectures.org/_images/numpy_indexing.png)

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Numpy Array Functions

In [18]:
arr = np.arange(10,101, 10)
arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

- 1. Median of ndarray:

In [19]:
np.median(arr)

55.0

- 2. Mean of ndarray:

In [20]:
np.mean(arr)

55.0

- 3. Standard Deviation of ndarray:

In [21]:
np.std(arr)

28.722813232690143

- 4. Correlation of two ndarrays with the same length:

In [22]:
y = np.array([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])
y

array([ 2,  1,  4,  5,  8, 12, 18, 25, 96, 48])

In [23]:
#return a matrix of Pearson correlation coefficients
np.corrcoef(arr, y)

array([[1.        , 0.75864029],
       [0.75864029, 1.        ]])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)